DesignPattern.CQRS.PresentationLayer/Controllers/PersonController.cs
using DesignPattern.CQRS.PresentationLayer.CQRS.Commands.PersonCommands;
using DesignPattern.CQRS.PresentationLayer.CQRS.Handlers.PersonHandlers;
using DesignPattern.CQRS.PresentationLayer.CQRS.Queries.PersonQueries;
using Microsoft.AspNetCore.Mvc;

namespace DesignPattern.CQRS.PresentationLayer.Controllers
{
    public class PersonController : Controller
    {
        private readonly GetPersonHumanResourceQueryHandler _getPersonHumanResourceQueryHandler;
        private readonly GetPersonByIDQueryHandler _getPersonByIDQueryHandler;
        private readonly CreatePersonHandler _createPersonHandler;
        private readonly DeletePersonHandler _deletePersonHandler;
        private readonly UpdatePersonHandler _updatePersonHandler;

        public PersonController(GetPersonHumanResourceQueryHandler getPersonHumanResourceQueryHandler, GetPersonByIDQueryHandler getPersonByIDQueryHandler, CreatePersonHandler createPersonHandler, DeletePersonHandler deletePersonHandler, UpdatePersonHandler updatePersonHandler)
        {
            _getPersonHumanResourceQueryHandler = getPersonHumanResourceQueryHandler;
            _getPersonByIDQueryHandler = getPersonByIDQueryHandler;
            _createPersonHandler = createPersonHandler;
            _deletePersonHandler = deletePersonHandler;
            _updatePersonHandler = updatePersonHandler;
        }

        public IActionResult Index()
        {
            var values = _getPersonHumanResourceQueryHandler.Handle(new GetPersonHumanResourceQuery());
            return View(values);
        }

        public IActionResult GetPerson(int id)
        {
            var values = _getPersonByIDQueryHandler.Handle(new GetPersonByIDQuery(id));
            return View(values);
        }

        [HttpGet]
        public IActionResult AddPerson()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddPerson(CreatePersonCommand command)
        {
            _createPersonHandler.Handle(command);
            return RedirectToAction("Index");
        }


        public IActionResult DeletePerson(int id)
        {
            _deletePersonHandler.Handle(new DeletePersonCommand(id));
            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult UpdatePerson(int id)
        {
            var values = _updatePersonHandler.FindPerson(id);
            return View(values);
        }

        [HttpPost]
        public IActionResult UpdatePerson(UpdatePersonCommand command)
        {
            _updatePersonHandler.Handle(command);
            return RedirectToAction("Index");
        }

    }
}

DesignPattern.CQRS.PresentationLayer/Views/Person/AddPerson.cshtml
@model DesignPattern.CQRS.PresentationLayer.CQRS.Commands.PersonCommands.CreatePersonCommand

@{
    Layout = null;
}

<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

<div class="container" style="margin-top:50px">
    <form method="post">
        <label>Personel Adı</label>
        <input type="text" class="form-control" asp-for="Name" />
        <br />
        <label>Personel Soyadı</label>
        <input type="text" class="form-control" asp-for="Surname" />
        <br />
        <label>Personel Maaşı</label>
        <input type="text" class="form-control" asp-for="Salary" />
        <br />
        <label>Personel Şehri</label>
        <input type="text" class="form-control" asp-for="City" />
        <br />
        <button class="btn btn-outline-primary">Personeli Kaydet</button>
    </form>
</div>

DesignPattern.CQRS.PresentationLayer/Views/Person/GetPerson.cshtml
@model GetPersonByIDQueryResult

@{
    Layout = null;
}

<div class="container">
    <label>Kişi ID</label>
    <input type="text" asp-for="PersonID" class="form-control" />
    <br />
    <label>Kişi Adı</label>
    <input type="text" asp-for="Name" class="form-control" />
    <br />
    <label>Kişi Soyadı</label>
    <input type="text" asp-for="Surname" class="form-control" />
    <br />
</div>

DesignPattern.CQRS.PresentationLayer/Views/Person/Index.cshtml
@model List<GetPersonHumanResourceQueryResult>

@{
    Layout = null;
}

<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />



<div class="container" style="margin-top:50px">
    <a asp-action="AddPerson" asp-controller="Person" class="btn btn-primary">Ekle</a>
    <br />
    <table class="table table-bordered mt-3">
        <tr>
            <th>#</th>
            <th>Ad</th>
            <th>Soyad</th>
            <th>Şehir</th>
            <th>Departman</th>
            <th>Telefon</th>
            <th>Mail</th>
            <th>İşlemler</th>
        </tr>
        @foreach (var item in Model)
        {
                <tr>
                    <td>@item.PersonID</td>
                    <td>@item.Name</td>
                    <td>@item.Surname</td>
                    <td>@item.City</td>
                    <td>@item.Department</td>
                    <td>@item.Phone</td>
                    <td>@item.Mail</td>
                    <td>
                        <a asp-action="UpdatePerson" asp-controller="Person" asp-route-id=@item.PersonID class="btn btn-success">Düzenle</a>

                        <a asp-action="DeletePerson" asp-controller="Person" asp-route-id=@item.PersonID class="btn btn-danger">Sil</a>

                    </td>
                </tr>
        }
    </table>
</div>

DesignPattern.CQRS.PresentationLayer/Views/Person/UpdatePerson.cshtml
@model DesignPattern.CQRS.PresentationLayer.CQRS.Commands.PersonCommands.UpdatePersonCommand

@{
    ViewData["Title"] = "UpdatePerson";
}

<h1>UpdatePerson</h1>

<h4>UpdatePersonCommand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdatePerson">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
                
                <input asp-for="PersonID" type="hidden" class="form-control" />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" class="form-control" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Departman" class="control-label"></label>
                <input asp-for="Departman" class="form-control" />
                <span asp-validation-for="Departman" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>